/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from './common';

export declare namespace EndpointStructs {
  export type EndpointMessageStruct = {
    sourceManagerAddress: BytesLike;
    recipientManagerAddress: BytesLike;
    managerPayload: BytesLike;
    endpointPayload: BytesLike;
  };

  export type EndpointMessageStructOutput = [string, string, string, string] & {
    sourceManagerAddress: string;
    recipientManagerAddress: string;
    managerPayload: string;
    endpointPayload: string;
  };

  export type EndpointInstructionStruct = {
    index: BigNumberish;
    payload: BytesLike;
  };

  export type EndpointInstructionStructOutput = [number, string] & {
    index: number;
    payload: string;
  };
}

export declare namespace WormholeEndpoint {
  export type WormholeEndpointInstructionStruct = {
    shouldSkipRelayerSend: boolean;
  };

  export type WormholeEndpointInstructionStructOutput = [boolean] & {
    shouldSkipRelayerSend: boolean;
  };
}

export interface WormholeEndpointInterface extends utils.Interface {
  functions: {
    'GAS_LIMIT()': FunctionFragment;
    'MIGRATES_IMMUTABLES_SLOT()': FunctionFragment;
    'MIGRATING_SLOT()': FunctionFragment;
    'PAUSER_ROLE_SLOT()': FunctionFragment;
    'PAUSE_SLOT()': FunctionFragment;
    'SPECIAL_RELAYING_ENABLED_CHAINS_SLOT()': FunctionFragment;
    'WORMHOLE_CONSUMED_VAAS_SLOT()': FunctionFragment;
    'WORMHOLE_EVM_CHAIN_IDS()': FunctionFragment;
    'WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT()': FunctionFragment;
    'WORMHOLE_SIBLINGS_SLOT()': FunctionFragment;
    'consistencyLevel()': FunctionFragment;
    'encodeWormholeEndpointInstruction((bool))': FunctionFragment;
    'getManagerOwner()': FunctionFragment;
    'getManagerToken()': FunctionFragment;
    'getMigratesImmutables()': FunctionFragment;
    'getWormholeSibling(uint16)': FunctionFragment;
    'initialize()': FunctionFragment;
    'isPaused()': FunctionFragment;
    'isSpecialRelayingEnabled(uint16)': FunctionFragment;
    'isVAAConsumed(bytes32)': FunctionFragment;
    'isWormholeEvmChain(uint16)': FunctionFragment;
    'isWormholeRelayingEnabled(uint16)': FunctionFragment;
    'manager()': FunctionFragment;
    'managerToken()': FunctionFragment;
    'migrate()': FunctionFragment;
    'owner()': FunctionFragment;
    'parseWormholeEndpointInstruction(bytes)': FunctionFragment;
    'pauser()': FunctionFragment;
    'quoteDeliveryPrice(uint16,(uint8,bytes))': FunctionFragment;
    'receiveMessage(bytes)': FunctionFragment;
    'receiveWormholeMessages(bytes,bytes[],bytes32,uint16,bytes32)': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'renouncePauser()': FunctionFragment;
    'sendMessage(uint16,(uint8,bytes),bytes,bytes32)': FunctionFragment;
    'setIsWormholeEvmChain(uint16)': FunctionFragment;
    'setIsWormholeRelayingEnabled(uint16,bool)': FunctionFragment;
    'setWormholeSibling(uint16,bytes32)': FunctionFragment;
    'specialRelayer()': FunctionFragment;
    'transferEndpointOwnership(address)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'transferPauserCapability(address)': FunctionFragment;
    'upgrade(address)': FunctionFragment;
    'wormhole()': FunctionFragment;
    'wormholeEndpoint_evmChainId()': FunctionFragment;
    'wormholeRelayer()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'GAS_LIMIT'
      | 'MIGRATES_IMMUTABLES_SLOT'
      | 'MIGRATING_SLOT'
      | 'PAUSER_ROLE_SLOT'
      | 'PAUSE_SLOT'
      | 'SPECIAL_RELAYING_ENABLED_CHAINS_SLOT'
      | 'WORMHOLE_CONSUMED_VAAS_SLOT'
      | 'WORMHOLE_EVM_CHAIN_IDS'
      | 'WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT'
      | 'WORMHOLE_SIBLINGS_SLOT'
      | 'consistencyLevel'
      | 'encodeWormholeEndpointInstruction'
      | 'getManagerOwner'
      | 'getManagerToken'
      | 'getMigratesImmutables'
      | 'getWormholeSibling'
      | 'initialize'
      | 'isPaused'
      | 'isSpecialRelayingEnabled'
      | 'isVAAConsumed'
      | 'isWormholeEvmChain'
      | 'isWormholeRelayingEnabled'
      | 'manager'
      | 'managerToken'
      | 'migrate'
      | 'owner'
      | 'parseWormholeEndpointInstruction'
      | 'pauser'
      | 'quoteDeliveryPrice'
      | 'receiveMessage'
      | 'receiveWormholeMessages'
      | 'renounceOwnership'
      | 'renouncePauser'
      | 'sendMessage'
      | 'setIsWormholeEvmChain'
      | 'setIsWormholeRelayingEnabled'
      | 'setWormholeSibling'
      | 'specialRelayer'
      | 'transferEndpointOwnership'
      | 'transferOwnership'
      | 'transferPauserCapability'
      | 'upgrade'
      | 'wormhole'
      | 'wormholeEndpoint_evmChainId'
      | 'wormholeRelayer',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'GAS_LIMIT', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'MIGRATES_IMMUTABLES_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIGRATING_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'PAUSER_ROLE_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'PAUSE_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'SPECIAL_RELAYING_ENABLED_CHAINS_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'WORMHOLE_CONSUMED_VAAS_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'WORMHOLE_EVM_CHAIN_IDS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'WORMHOLE_SIBLINGS_SLOT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'consistencyLevel',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'encodeWormholeEndpointInstruction',
    values: [WormholeEndpoint.WormholeEndpointInstructionStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'getManagerOwner',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getManagerToken',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getMigratesImmutables',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getWormholeSibling',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'initialize',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'isPaused', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'isSpecialRelayingEnabled',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'isVAAConsumed',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isWormholeEvmChain',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'isWormholeRelayingEnabled',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'manager', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'managerToken',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'migrate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'parseWormholeEndpointInstruction',
    values: [BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'pauser', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'quoteDeliveryPrice',
    values: [BigNumberish, EndpointStructs.EndpointInstructionStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'receiveMessage',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'receiveWormholeMessages',
    values: [BytesLike, BytesLike[], BytesLike, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renouncePauser',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'sendMessage',
    values: [
      BigNumberish,
      EndpointStructs.EndpointInstructionStruct,
      BytesLike,
      BytesLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'setIsWormholeEvmChain',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setIsWormholeRelayingEnabled',
    values: [BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setWormholeSibling',
    values: [BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'specialRelayer',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'transferEndpointOwnership',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferPauserCapability',
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: 'upgrade', values: [string]): string;
  encodeFunctionData(functionFragment: 'wormhole', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'wormholeEndpoint_evmChainId',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'wormholeRelayer',
    values?: undefined,
  ): string;

  decodeFunctionResult(functionFragment: 'GAS_LIMIT', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'MIGRATES_IMMUTABLES_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIGRATING_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'PAUSER_ROLE_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'PAUSE_SLOT', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'SPECIAL_RELAYING_ENABLED_CHAINS_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'WORMHOLE_CONSUMED_VAAS_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'WORMHOLE_EVM_CHAIN_IDS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'WORMHOLE_SIBLINGS_SLOT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'consistencyLevel',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'encodeWormholeEndpointInstruction',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getManagerOwner',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getManagerToken',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getMigratesImmutables',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getWormholeSibling',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isPaused', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isSpecialRelayingEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isVAAConsumed',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isWormholeEvmChain',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isWormholeRelayingEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'manager', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'managerToken',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'migrate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'parseWormholeEndpointInstruction',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'pauser', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'quoteDeliveryPrice',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'receiveMessage',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'receiveWormholeMessages',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renouncePauser',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'sendMessage',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setIsWormholeEvmChain',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setIsWormholeRelayingEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setWormholeSibling',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'specialRelayer',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferEndpointOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferPauserCapability',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'upgrade', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'wormhole', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'wormholeEndpoint_evmChainId',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'wormholeRelayer',
    data: BytesLike,
  ): Result;

  events: {
    'AdminChanged(address,address)': EventFragment;
    'BeaconUpgraded(address)': EventFragment;
    'Initialized(uint64)': EventFragment;
    'NotPaused(bool)': EventFragment;
    'OwnershipTransferred(address,address)': EventFragment;
    'Paused(bool)': EventFragment;
    'PauserTransferred(address,address)': EventFragment;
    'ReceivedMessage(bytes32,uint16,bytes32,uint64)': EventFragment;
    'ReceivedRelayedMessage(bytes32,uint16,bytes32)': EventFragment;
    'SendEndpointMessage(uint16,(bytes32,bytes32,bytes,bytes))': EventFragment;
    'SetIsSpecialRelayingEnabled(uint16,bool)': EventFragment;
    'SetIsWormholeEvmChain(uint16)': EventFragment;
    'SetIsWormholeRelayingEnabled(uint16,bool)': EventFragment;
    'SetWormholeSibling(uint16,bytes32,bytes32)': EventFragment;
    'Upgraded(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'AdminChanged'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'BeaconUpgraded'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'NotPaused'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Paused'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'PauserTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ReceivedMessage'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'ReceivedRelayedMessage'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SendEndpointMessage'): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: 'SetIsSpecialRelayingEnabled',
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SetIsWormholeEvmChain'): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: 'SetIsWormholeRelayingEnabled',
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SetWormholeSibling'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Upgraded'): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NotPausedEventObject {
  notPaused: boolean;
}
export type NotPausedEvent = TypedEvent<[boolean], NotPausedEventObject>;

export type NotPausedEventFilter = TypedEventFilter<NotPausedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  paused: boolean;
}
export type PausedEvent = TypedEvent<[boolean], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PauserTransferredEventObject {
  oldPauser: string;
  newPauser: string;
}
export type PauserTransferredEvent = TypedEvent<
  [string, string],
  PauserTransferredEventObject
>;

export type PauserTransferredEventFilter =
  TypedEventFilter<PauserTransferredEvent>;

export interface ReceivedMessageEventObject {
  digest: string;
  emitterChainId: number;
  emitterAddress: string;
  sequence: BigNumber;
}
export type ReceivedMessageEvent = TypedEvent<
  [string, number, string, BigNumber],
  ReceivedMessageEventObject
>;

export type ReceivedMessageEventFilter = TypedEventFilter<ReceivedMessageEvent>;

export interface ReceivedRelayedMessageEventObject {
  digest: string;
  emitterChainId: number;
  emitterAddress: string;
}
export type ReceivedRelayedMessageEvent = TypedEvent<
  [string, number, string],
  ReceivedRelayedMessageEventObject
>;

export type ReceivedRelayedMessageEventFilter =
  TypedEventFilter<ReceivedRelayedMessageEvent>;

export interface SendEndpointMessageEventObject {
  recipientChain: number;
  message: EndpointStructs.EndpointMessageStructOutput;
}
export type SendEndpointMessageEvent = TypedEvent<
  [number, EndpointStructs.EndpointMessageStructOutput],
  SendEndpointMessageEventObject
>;

export type SendEndpointMessageEventFilter =
  TypedEventFilter<SendEndpointMessageEvent>;

export interface SetIsSpecialRelayingEnabledEventObject {
  chainId: number;
  isRelayingEnabled: boolean;
}
export type SetIsSpecialRelayingEnabledEvent = TypedEvent<
  [number, boolean],
  SetIsSpecialRelayingEnabledEventObject
>;

export type SetIsSpecialRelayingEnabledEventFilter =
  TypedEventFilter<SetIsSpecialRelayingEnabledEvent>;

export interface SetIsWormholeEvmChainEventObject {
  chainId: number;
}
export type SetIsWormholeEvmChainEvent = TypedEvent<
  [number],
  SetIsWormholeEvmChainEventObject
>;

export type SetIsWormholeEvmChainEventFilter =
  TypedEventFilter<SetIsWormholeEvmChainEvent>;

export interface SetIsWormholeRelayingEnabledEventObject {
  chainId: number;
  isRelayingEnabled: boolean;
}
export type SetIsWormholeRelayingEnabledEvent = TypedEvent<
  [number, boolean],
  SetIsWormholeRelayingEnabledEventObject
>;

export type SetIsWormholeRelayingEnabledEventFilter =
  TypedEventFilter<SetIsWormholeRelayingEnabledEvent>;

export interface SetWormholeSiblingEventObject {
  chainId: number;
  oldSiblingContract: string;
  siblingContract: string;
}
export type SetWormholeSiblingEvent = TypedEvent<
  [number, string, string],
  SetWormholeSiblingEventObject
>;

export type SetWormholeSiblingEventFilter =
  TypedEventFilter<SetWormholeSiblingEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface WormholeEndpoint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WormholeEndpointInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GAS_LIMIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIGRATES_IMMUTABLES_SLOT(overrides?: CallOverrides): Promise<[string]>;

    MIGRATING_SLOT(overrides?: CallOverrides): Promise<[string]>;

    PAUSER_ROLE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    PAUSE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    SPECIAL_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<[string]>;

    WORMHOLE_CONSUMED_VAAS_SLOT(overrides?: CallOverrides): Promise<[string]>;

    WORMHOLE_EVM_CHAIN_IDS(overrides?: CallOverrides): Promise<[string]>;

    WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<[string]>;

    WORMHOLE_SIBLINGS_SLOT(overrides?: CallOverrides): Promise<[string]>;

    consistencyLevel(overrides?: CallOverrides): Promise<[number]>;

    encodeWormholeEndpointInstruction(
      instruction: WormholeEndpoint.WormholeEndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    getManagerOwner(overrides?: CallOverrides): Promise<[string]>;

    getManagerToken(overrides?: CallOverrides): Promise<[string]>;

    getMigratesImmutables(overrides?: CallOverrides): Promise<[boolean]>;

    getWormholeSibling(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    initialize(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    isPaused(overrides?: CallOverrides): Promise<[boolean]>;

    isSpecialRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isVAAConsumed(
      hash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isWormholeRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    managerToken(overrides?: CallOverrides): Promise<[string]>;

    migrate(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    parseWormholeEndpointInstruction(
      encoded: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [WormholeEndpoint.WormholeEndpointInstructionStructOutput] & {
        instruction: WormholeEndpoint.WormholeEndpointInstructionStructOutput;
      }
    >;

    pauser(overrides?: CallOverrides): Promise<[string]>;

    quoteDeliveryPrice(
      targetChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    receiveMessage(
      encodedMessage: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    receiveWormholeMessages(
      payload: BytesLike,
      additionalMessages: BytesLike[],
      sourceAddress: BytesLike,
      sourceChain: BigNumberish,
      deliveryHash: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    renouncePauser(
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    sendMessage(
      recipientChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      managerMessage: BytesLike,
      recipientManagerAddress: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<ContractTransaction>;

    setIsWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    setIsWormholeRelayingEnabled(
      chainId: BigNumberish,
      isEnabled: boolean,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    setWormholeSibling(
      siblingChainId: BigNumberish,
      siblingContract: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    specialRelayer(overrides?: CallOverrides): Promise<[string]>;

    transferEndpointOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    transferPauserCapability(
      newPauser: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    upgrade(
      newImplementation: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    wormhole(overrides?: CallOverrides): Promise<[string]>;

    wormholeEndpoint_evmChainId(
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    wormholeRelayer(overrides?: CallOverrides): Promise<[string]>;
  };

  GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

  MIGRATES_IMMUTABLES_SLOT(overrides?: CallOverrides): Promise<string>;

  MIGRATING_SLOT(overrides?: CallOverrides): Promise<string>;

  PAUSER_ROLE_SLOT(overrides?: CallOverrides): Promise<string>;

  PAUSE_SLOT(overrides?: CallOverrides): Promise<string>;

  SPECIAL_RELAYING_ENABLED_CHAINS_SLOT(
    overrides?: CallOverrides,
  ): Promise<string>;

  WORMHOLE_CONSUMED_VAAS_SLOT(overrides?: CallOverrides): Promise<string>;

  WORMHOLE_EVM_CHAIN_IDS(overrides?: CallOverrides): Promise<string>;

  WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT(
    overrides?: CallOverrides,
  ): Promise<string>;

  WORMHOLE_SIBLINGS_SLOT(overrides?: CallOverrides): Promise<string>;

  consistencyLevel(overrides?: CallOverrides): Promise<number>;

  encodeWormholeEndpointInstruction(
    instruction: WormholeEndpoint.WormholeEndpointInstructionStruct,
    overrides?: CallOverrides,
  ): Promise<string>;

  getManagerOwner(overrides?: CallOverrides): Promise<string>;

  getManagerToken(overrides?: CallOverrides): Promise<string>;

  getMigratesImmutables(overrides?: CallOverrides): Promise<boolean>;

  getWormholeSibling(
    chainId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  initialize(
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  isPaused(overrides?: CallOverrides): Promise<boolean>;

  isSpecialRelayingEnabled(
    chainId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  isVAAConsumed(hash: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  isWormholeEvmChain(
    chainId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  isWormholeRelayingEnabled(
    chainId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  manager(overrides?: CallOverrides): Promise<string>;

  managerToken(overrides?: CallOverrides): Promise<string>;

  migrate(
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  parseWormholeEndpointInstruction(
    encoded: BytesLike,
    overrides?: CallOverrides,
  ): Promise<WormholeEndpoint.WormholeEndpointInstructionStructOutput>;

  pauser(overrides?: CallOverrides): Promise<string>;

  quoteDeliveryPrice(
    targetChain: BigNumberish,
    instruction: EndpointStructs.EndpointInstructionStruct,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  receiveMessage(
    encodedMessage: BytesLike,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  receiveWormholeMessages(
    payload: BytesLike,
    additionalMessages: BytesLike[],
    sourceAddress: BytesLike,
    sourceChain: BigNumberish,
    deliveryHash: BytesLike,
    overrides?: PayableOverrides & { from?: string },
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  renouncePauser(
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  sendMessage(
    recipientChain: BigNumberish,
    instruction: EndpointStructs.EndpointInstructionStruct,
    managerMessage: BytesLike,
    recipientManagerAddress: BytesLike,
    overrides?: PayableOverrides & { from?: string },
  ): Promise<ContractTransaction>;

  setIsWormholeEvmChain(
    chainId: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  setIsWormholeRelayingEnabled(
    chainId: BigNumberish,
    isEnabled: boolean,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  setWormholeSibling(
    siblingChainId: BigNumberish,
    siblingContract: BytesLike,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  specialRelayer(overrides?: CallOverrides): Promise<string>;

  transferEndpointOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  transferPauserCapability(
    newPauser: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  upgrade(
    newImplementation: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  wormhole(overrides?: CallOverrides): Promise<string>;

  wormholeEndpoint_evmChainId(overrides?: CallOverrides): Promise<BigNumber>;

  wormholeRelayer(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    MIGRATES_IMMUTABLES_SLOT(overrides?: CallOverrides): Promise<string>;

    MIGRATING_SLOT(overrides?: CallOverrides): Promise<string>;

    PAUSER_ROLE_SLOT(overrides?: CallOverrides): Promise<string>;

    PAUSE_SLOT(overrides?: CallOverrides): Promise<string>;

    SPECIAL_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<string>;

    WORMHOLE_CONSUMED_VAAS_SLOT(overrides?: CallOverrides): Promise<string>;

    WORMHOLE_EVM_CHAIN_IDS(overrides?: CallOverrides): Promise<string>;

    WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<string>;

    WORMHOLE_SIBLINGS_SLOT(overrides?: CallOverrides): Promise<string>;

    consistencyLevel(overrides?: CallOverrides): Promise<number>;

    encodeWormholeEndpointInstruction(
      instruction: WormholeEndpoint.WormholeEndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<string>;

    getManagerOwner(overrides?: CallOverrides): Promise<string>;

    getManagerToken(overrides?: CallOverrides): Promise<string>;

    getMigratesImmutables(overrides?: CallOverrides): Promise<boolean>;

    getWormholeSibling(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    isPaused(overrides?: CallOverrides): Promise<boolean>;

    isSpecialRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    isVAAConsumed(hash: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    isWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    isWormholeRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    manager(overrides?: CallOverrides): Promise<string>;

    managerToken(overrides?: CallOverrides): Promise<string>;

    migrate(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    parseWormholeEndpointInstruction(
      encoded: BytesLike,
      overrides?: CallOverrides,
    ): Promise<WormholeEndpoint.WormholeEndpointInstructionStructOutput>;

    pauser(overrides?: CallOverrides): Promise<string>;

    quoteDeliveryPrice(
      targetChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    receiveMessage(
      encodedMessage: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    receiveWormholeMessages(
      payload: BytesLike,
      additionalMessages: BytesLike[],
      sourceAddress: BytesLike,
      sourceChain: BigNumberish,
      deliveryHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renouncePauser(overrides?: CallOverrides): Promise<void>;

    sendMessage(
      recipientChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      managerMessage: BytesLike,
      recipientManagerAddress: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    setIsWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setIsWormholeRelayingEnabled(
      chainId: BigNumberish,
      isEnabled: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;

    setWormholeSibling(
      siblingChainId: BigNumberish,
      siblingContract: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    specialRelayer(overrides?: CallOverrides): Promise<string>;

    transferEndpointOwnership(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    transferPauserCapability(
      newPauser: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    upgrade(
      newImplementation: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    wormhole(overrides?: CallOverrides): Promise<string>;

    wormholeEndpoint_evmChainId(overrides?: CallOverrides): Promise<BigNumber>;

    wormholeRelayer(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    'AdminChanged(address,address)'(
      previousAdmin?: null,
      newAdmin?: null,
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null,
    ): AdminChangedEventFilter;

    'BeaconUpgraded(address)'(
      beacon?: string | null,
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(beacon?: string | null): BeaconUpgradedEventFilter;

    'Initialized(uint64)'(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    'NotPaused(bool)'(notPaused?: null): NotPausedEventFilter;
    NotPaused(notPaused?: null): NotPausedEventFilter;

    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;

    'Paused(bool)'(paused?: null): PausedEventFilter;
    Paused(paused?: null): PausedEventFilter;

    'PauserTransferred(address,address)'(
      oldPauser?: string | null,
      newPauser?: string | null,
    ): PauserTransferredEventFilter;
    PauserTransferred(
      oldPauser?: string | null,
      newPauser?: string | null,
    ): PauserTransferredEventFilter;

    'ReceivedMessage(bytes32,uint16,bytes32,uint64)'(
      digest?: null,
      emitterChainId?: null,
      emitterAddress?: null,
      sequence?: null,
    ): ReceivedMessageEventFilter;
    ReceivedMessage(
      digest?: null,
      emitterChainId?: null,
      emitterAddress?: null,
      sequence?: null,
    ): ReceivedMessageEventFilter;

    'ReceivedRelayedMessage(bytes32,uint16,bytes32)'(
      digest?: null,
      emitterChainId?: null,
      emitterAddress?: null,
    ): ReceivedRelayedMessageEventFilter;
    ReceivedRelayedMessage(
      digest?: null,
      emitterChainId?: null,
      emitterAddress?: null,
    ): ReceivedRelayedMessageEventFilter;

    'SendEndpointMessage(uint16,(bytes32,bytes32,bytes,bytes))'(
      recipientChain?: null,
      message?: null,
    ): SendEndpointMessageEventFilter;
    SendEndpointMessage(
      recipientChain?: null,
      message?: null,
    ): SendEndpointMessageEventFilter;

    'SetIsSpecialRelayingEnabled(uint16,bool)'(
      chainId?: null,
      isRelayingEnabled?: null,
    ): SetIsSpecialRelayingEnabledEventFilter;
    SetIsSpecialRelayingEnabled(
      chainId?: null,
      isRelayingEnabled?: null,
    ): SetIsSpecialRelayingEnabledEventFilter;

    'SetIsWormholeEvmChain(uint16)'(
      chainId?: null,
    ): SetIsWormholeEvmChainEventFilter;
    SetIsWormholeEvmChain(chainId?: null): SetIsWormholeEvmChainEventFilter;

    'SetIsWormholeRelayingEnabled(uint16,bool)'(
      chainId?: null,
      isRelayingEnabled?: null,
    ): SetIsWormholeRelayingEnabledEventFilter;
    SetIsWormholeRelayingEnabled(
      chainId?: null,
      isRelayingEnabled?: null,
    ): SetIsWormholeRelayingEnabledEventFilter;

    'SetWormholeSibling(uint16,bytes32,bytes32)'(
      chainId?: null,
      oldSiblingContract?: null,
      siblingContract?: null,
    ): SetWormholeSiblingEventFilter;
    SetWormholeSibling(
      chainId?: null,
      oldSiblingContract?: null,
      siblingContract?: null,
    ): SetWormholeSiblingEventFilter;

    'Upgraded(address)'(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    MIGRATES_IMMUTABLES_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    MIGRATING_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSER_ROLE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    SPECIAL_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    WORMHOLE_CONSUMED_VAAS_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    WORMHOLE_EVM_CHAIN_IDS(overrides?: CallOverrides): Promise<BigNumber>;

    WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    WORMHOLE_SIBLINGS_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    consistencyLevel(overrides?: CallOverrides): Promise<BigNumber>;

    encodeWormholeEndpointInstruction(
      instruction: WormholeEndpoint.WormholeEndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getManagerOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getManagerToken(overrides?: CallOverrides): Promise<BigNumber>;

    getMigratesImmutables(overrides?: CallOverrides): Promise<BigNumber>;

    getWormholeSibling(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    initialize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    isPaused(overrides?: CallOverrides): Promise<BigNumber>;

    isSpecialRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isVAAConsumed(
      hash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isWormholeRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    managerToken(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    parseWormholeEndpointInstruction(
      encoded: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    pauser(overrides?: CallOverrides): Promise<BigNumber>;

    quoteDeliveryPrice(
      targetChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    receiveMessage(
      encodedMessage: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    receiveWormholeMessages(
      payload: BytesLike,
      additionalMessages: BytesLike[],
      sourceAddress: BytesLike,
      sourceChain: BigNumberish,
      deliveryHash: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    renouncePauser(
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    sendMessage(
      recipientChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      managerMessage: BytesLike,
      recipientManagerAddress: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<BigNumber>;

    setIsWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    setIsWormholeRelayingEnabled(
      chainId: BigNumberish,
      isEnabled: boolean,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    setWormholeSibling(
      siblingChainId: BigNumberish,
      siblingContract: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    specialRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    transferEndpointOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    transferPauserCapability(
      newPauser: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    upgrade(
      newImplementation: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    wormhole(overrides?: CallOverrides): Promise<BigNumber>;

    wormholeEndpoint_evmChainId(overrides?: CallOverrides): Promise<BigNumber>;

    wormholeRelayer(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    GAS_LIMIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIGRATES_IMMUTABLES_SLOT(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    MIGRATING_SLOT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PAUSER_ROLE_SLOT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PAUSE_SLOT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SPECIAL_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    WORMHOLE_CONSUMED_VAAS_SLOT(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    WORMHOLE_EVM_CHAIN_IDS(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    WORMHOLE_RELAYING_ENABLED_CHAINS_SLOT(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    WORMHOLE_SIBLINGS_SLOT(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    consistencyLevel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    encodeWormholeEndpointInstruction(
      instruction: WormholeEndpoint.WormholeEndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getManagerOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getManagerToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMigratesImmutables(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getWormholeSibling(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    isPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSpecialRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isVAAConsumed(
      hash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isWormholeRelayingEnabled(
      chainId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    managerToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrate(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    parseWormholeEndpointInstruction(
      encoded: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    pauser(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteDeliveryPrice(
      targetChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    receiveMessage(
      encodedMessage: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    receiveWormholeMessages(
      payload: BytesLike,
      additionalMessages: BytesLike[],
      sourceAddress: BytesLike,
      sourceChain: BigNumberish,
      deliveryHash: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    renouncePauser(
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    sendMessage(
      recipientChain: BigNumberish,
      instruction: EndpointStructs.EndpointInstructionStruct,
      managerMessage: BytesLike,
      recipientManagerAddress: BytesLike,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    setIsWormholeEvmChain(
      chainId: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    setIsWormholeRelayingEnabled(
      chainId: BigNumberish,
      isEnabled: boolean,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    setWormholeSibling(
      siblingChainId: BigNumberish,
      siblingContract: BytesLike,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    specialRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferEndpointOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    transferPauserCapability(
      newPauser: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    upgrade(
      newImplementation: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    wormhole(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wormholeEndpoint_evmChainId(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    wormholeRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
