[build]
command = "bun run build:netlify"
publish = "build"

[build.environment]
BUN_VERSION = "1.3.4"

[context.mainnet]
command = "bun run build:netlify"

[context.production]
command = "bun run build:netlify"
