import type { ChainsConfig } from '../types';

export const TESTNET_CHAINS: ChainsConfig = {
  Bsc: {
    displayName: 'BSC',
    explorerUrl: 'https://testnet.bscscan.com/',
    explorerName: 'BscScan',
    icon: 'Bsc',
    symbol: 'BSC',
    sdkName: 'Bsc',
  },
  Avalanche: {
    displayName: 'Fuji',
    explorerUrl: 'https://testnet.snowtrace.io/',
    explorerName: 'Snowtrace',
    icon: 'Avalanche',
    symbol: 'AVAX',
    sdkName: 'Avalanche',
  },
  Fantom: {
    displayName: 'Fantom',
    explorerUrl: 'https://testnet.ftmscan.com/',
    explorerName: 'FtmScan',
    icon: 'Fantom',
    symbol: 'FTM',
    sdkName: 'Fantom',
  },
  Celo: {
    displayName: 'Alfajores',
    explorerUrl: 'https://explorer.celo.org/alfajores/',
    explorerName: 'Celo Explorer',
    icon: 'Celo',
    symbol: 'CELO',
    sdkName: 'Celo',
  },
  Moonbeam: {
    displayName: 'Moonbase',
    explorerUrl: 'https://moonbase.moonscan.io/',
    explorerName: 'Moonscan',
    icon: 'Moonbeam',
    symbol: 'GLMR',
    sdkName: 'Moonbeam',
  },
  Solana: {
    displayName: 'Solana',
    explorerUrl: 'https://explorer.solana.com/?cluster=devnet',
    explorerName: 'Solana Explorer',
    icon: 'Solana',
    symbol: 'SOL',
    sdkName: 'Solana',
  },
  Sui: {
    displayName: 'Sui',
    explorerUrl: 'https://suiscan.xyz/testnet/',
    explorerName: 'Suiscan',
    icon: 'Sui',
    symbol: 'SUI',
    sdkName: 'Sui',
  },
  Aptos: {
    displayName: 'Aptos',
    explorerUrl: 'https://explorer.aptoslabs.com/',
    explorerName: 'Aptos Explorer',
    icon: 'Aptos',
    symbol: 'APT',
    sdkName: 'Aptos',
  },
  Klaytn: {
    displayName: 'Kaia',
    explorerUrl: 'https://kairos.kaiascan.io/',
    explorerName: 'KaiaScan',
    icon: 'Klaytn',
    symbol: 'KAIA',
    sdkName: 'Klaytn',
  },
  Sepolia: {
    displayName: 'Sepolia',
    explorerUrl: 'https://sepolia.etherscan.io/',
    explorerName: 'Etherscan',
    icon: 'Ethereum',
    symbol: 'ETH',
    sdkName: 'Sepolia',
  },
  ArbitrumSepolia: {
    displayName: 'Arbitrum Sepolia',
    explorerUrl: 'https://sepolia.arbiscan.io/',
    explorerName: 'Etherscan',
    icon: 'Arbitrum',
    symbol: 'ARB',
    sdkName: 'ArbitrumSepolia',
  },
  BaseSepolia: {
    displayName: 'Base Sepolia',
    explorerUrl: 'https://base-sepolia.blockscout.com/',
    explorerName: 'Etherscan',
    icon: 'Base',
    symbol: 'BASE',
    sdkName: 'BaseSepolia',
  },
  OptimismSepolia: {
    displayName: 'Optimism Sepolia',
    explorerUrl: 'https://sepolia-optimistic.etherscan.io/',
    explorerName: 'Etherscan',
    icon: 'Optimism',
    symbol: 'OP',
    sdkName: 'OptimismSepolia',
  },
  Scroll: {
    displayName: 'Scroll',
    explorerUrl: 'https://sepolia.scrollscan.dev/',
    explorerName: 'Scrollscan',
    icon: 'Scroll',
    symbol: 'SCR',
    sdkName: 'Scroll',
  },
  Xlayer: {
    displayName: 'X Layer',
    explorerUrl: 'https://www.okx.com/web3/explorer/xlayer-test/',
    explorerName: 'OKX Explorer',
    icon: 'Xlayer',
    symbol: 'OKX',
    sdkName: 'Xlayer',
  },
  Mantle: {
    displayName: 'Mantle',
    explorerUrl: 'https://explorer.testnet.mantle.xyz/',
    explorerName: 'Mantle Explorer',
    icon: 'Mantle',
    symbol: 'MNT',
    sdkName: 'Mantle',
  },
  Worldchain: {
    displayName: 'World Chain',
    explorerUrl: 'https://worldchain-sepolia.explorer.alchemy.com/',
    explorerName: 'World Scan',
    icon: 'Worldchain',
    sdkName: 'Worldchain',
    symbol: 'WORLD',
  },
  Unichain: {
    displayName: 'Unichain',
    explorerUrl: 'https://unichain-sepolia.blockscout.com/',
    explorerName: 'Unichain Explorer',
    icon: 'Unichain',
    symbol: 'UNI',
    sdkName: 'Unichain',
  },
  Mezo: {
    displayName: 'Mezo',
    explorerUrl: 'https://explorer.test.mezo.org/',
    explorerName: 'Mezo Explorer',
    icon: 'Mezo',
    sdkName: 'Mezo',
    symbol: 'MEZO',
  },
  Linea: {
    displayName: 'Linea',
    sdkName: 'Linea',
    explorerUrl: 'https://sepolia.lineascan.build/',
    explorerName: 'Lineascan',
    icon: 'Linea',
    symbol: 'LINEA',
  },
  Sonic: {
    displayName: 'Sonic',
    sdkName: 'Sonic',
    explorerUrl: 'https://testnet.sonicscan.org/',
    explorerName: 'Sonicscan',
    icon: 'Sonic',
    symbol: 'S',
  },
  Seievm: {
    displayName: 'SeiEVM',
    explorerUrl: 'https://seitrace.com/?chain=atlantic-2',
    explorerName: 'Seitrace',
    icon: 'Seievm',
    sdkName: 'Seievm',
    symbol: 'SEI',
  },
  Plume: {
    displayName: 'Plume',
    sdkName: 'Plume',
    explorerUrl: 'https://testnet-explorer.plume.org',
    explorerName: 'Plume Explorer',
    icon: 'Plume',
    symbol: 'PLUME',
  },
  Fogo: {
    displayName: 'Fogo',
    sdkName: 'Fogo',
    explorerUrl: 'https://explorer.fogo.io/',
    explorerName: 'Fogo Explorer',
    icon: 'Fogo',
    symbol: 'FOGO',
  },
  XRPLEVM: {
    displayName: 'XRPL Testnet',
    sdkName: 'XRPLEVM',
    icon: 'XRPLEVM',
    explorerUrl: 'https://testnet.xrpl.org/',
    explorerName: 'XRPL Explorer',
    symbol: 'XRP',
  },
};
