import {
  Network as Environment,
  Contracts,
  CONTRACTS,
} from '@certusone/wormhole-sdk';
import { WormholeConfig, Context, ChainConfig, TokenConfig } from '../types';
import AcalaIcon from '../../icons/tokens/acala.svg';
import AlgoIcon from '../../icons/tokens/algorand.svg';
import AptosIcon from '../../icons/tokens/aptos.svg';
import ArbitrumIcon from '../../icons/tokens/arbitrum.svg';
import AuroraIcon from '../../icons/tokens/aurora.svg';
import AvaxIcon from '../../icons/tokens/avax.svg';
import BscIcon from '../../icons/tokens/bsc.svg';
import CeloIcon from '../../icons/tokens/celo.svg';
import EthIcon from '../../icons/tokens/eth.svg';
import FantomIcon from '../../icons/tokens/fantom.svg';
import InjectiveIcon from '../../icons/tokens/injective.svg';
import KaruraIcon from '../../icons/tokens/karura.svg';
import KlaytnIcon from '../../icons/tokens/klaytn.svg';
import MoonbeamIcon from '../../icons/tokens/moonbeam.svg';
import NearIcon from '../../icons/tokens/near.svg';
import NeonIcon from '../../icons/tokens/neon.svg';
import OasisIcon from '../../icons/tokens/oasis-network-rose-logo.svg';
import OsmosisIcon from '../../icons/tokens/osmosis.svg';
import PolygonIcon from '../../icons/tokens/polygon.svg';
import SolanaIcon from '../../icons/tokens/solana.svg';
import SuiIcon from '../../icons/tokens/sui.png';
import TerraIcon from '../../icons/tokens/terra.svg';
import Terra2Icon from '../../icons/tokens/terra2.svg';
import XplaIcon from '../../icons/tokens/xpla.svg';

import BnbIcon from '../../icons/tokens/bnb.svg';

// https://book.wormhole.com/reference/contracts.html
export const MAINNET_CHAINS = {
  solana: 1,
  ethereum: 2,
  terra: 3,
  bsc: 4,
  polygon: 5,
  avalanche: 6,
  oasis: 7,
  algorand: 8,
  aurora: 9,
  fantom: 10,
  karura: 11,
  acala: 12,
  klaytn: 13,
  celo: 14,
  near: 15,
  moonbeam: 16,
  neon: 17,
  terra2: 18,
  injective: 19,
  osmosis: 20,
  sui: 21,
  aptos: 22,
  arbitrum: 23,
  optimism: 24,
  gnosis: 25,
  pythnet: 26,
  xpla: 28,
  btc: 29,
  wormchain: 3104,
} as const;

export type MainnetChainName = keyof typeof MAINNET_CHAINS;
export type MainnetChainId = (typeof MAINNET_CHAINS)[MainnetChainName];

export type ChainContracts = {
  [chain in MainnetChainName]: Contracts;
};

const MAINNET: { [chain in MainnetChainName]: ChainConfig } = {
  solana: {
    key: 'solana',
    id: 1,
    context: Context.SOLANA,
    contracts: CONTRACTS.MAINNET.solana,
    icon: SolanaIcon,
    displayName: 'Solana',
    explorerUrl: 'https://explorer.solana.com/',
    explorerName: 'Solana Explorer',
    gasToken: 'SOL', // TODO:
    chainId: 0,
  },
  ethereum: {
    key: 'ethereum',
    id: 2,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.ethereum,
    icon: EthIcon,
    displayName: 'Ethereum',
    explorerUrl: 'https://etherscan.io/',
    explorerName: 'Etherscan',
    gasToken: 'ETH',
    chainId: 1,
  },
  terra: {
    key: 'terra',
    id: 3,
    context: Context.TERRA,
    contracts: CONTRACTS.MAINNET.terra,
    icon: TerraIcon,
    displayName: 'Terra',
    explorerUrl: 'https://atomscan.com/terra',
    explorerName: 'ATOMScan',
    gasToken: 'ATOM',
    chainId: 0,
  },
  bsc: {
    key: 'bsc',
    id: 4,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.bsc,
    icon: BscIcon,
    displayName: 'BSC',
    explorerUrl: 'https://bscscan.com/',
    explorerName: 'BscScan',
    gasToken: 'BNB',
    chainId: 56,
  },
  polygon: {
    key: 'polygon',
    id: 5,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.polygon,
    icon: PolygonIcon,
    displayName: 'Polygon',
    explorerUrl: 'https://polygonscan.com/',
    explorerName: 'PolygonScan',
    gasToken: 'MATIC',
    chainId: 137,
  },
  avalanche: {
    key: 'avalanche',
    id: 6,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.avalanche,
    icon: AvaxIcon,
    displayName: 'Avalanche',
    explorerUrl: 'https://snowtrace.io/',
    explorerName: 'Snowtrace',
    gasToken: 'WAVAX',
    chainId: 43114,
  },
  oasis: {
    key: 'oasis',
    id: 7,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.oasis,
    icon: OasisIcon,
    displayName: 'Oasis',
    explorerUrl: 'https://www.oasisscan.com/',
    explorerName: 'Oasis Scan',
    gasToken: 'ROSE',
    chainId: 26863,
  },
  algorand: {
    key: 'algorand',
    id: 8,
    context: Context.ALGORAND,
    contracts: CONTRACTS.MAINNET.algorand,
    icon: AlgoIcon,
    displayName: 'Algorand',
    explorerUrl: 'https://algoexplorer.io/',
    explorerName: 'AlgoExplorer',
    gasToken: 'ALGO',
    chainId: 0,
  },
  aurora: {
    key: 'aurora',
    id: 9,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.aurora,
    icon: AuroraIcon,
    displayName: 'Aurora',
    explorerUrl: 'https://explorer.mainnet.aurora.dev/',
    explorerName: 'Aurora Explorer',
    gasToken: 'NEAR',
    chainId: 1313161554,
  },
  fantom: {
    key: 'fantom',
    id: 10,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.fantom,
    icon: FantomIcon,
    displayName: 'Fantom',
    explorerUrl: 'https://ftmscan.com/',
    explorerName: 'FTMscan',
    gasToken: 'FTM',
    chainId: 250,
  },
  karura: {
    key: 'karura',
    id: 11,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.karura,
    icon: KaruraIcon,
    displayName: 'Karura',
    explorerUrl: 'https://karura.subscan.io/',
    explorerName: 'Karura Explorer',
    gasToken: 'KAR',
    chainId: 686,
  },
  acala: {
    key: 'acala',
    id: 12,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.acala,
    icon: AcalaIcon,
    displayName: 'Acala',
    explorerUrl: 'https://acala.subscan.io/',
    explorerName: 'Acala Explorer',
    gasToken: 'ACA',
    chainId: 787,
  },
  klaytn: {
    key: 'klaytn',
    id: 13,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.klaytn,
    icon: KlaytnIcon,
    displayName: 'Klaytn',
    explorerUrl: 'https://scope.klaytn.com/',
    explorerName: 'KlaytnScope',
    gasToken: 'KLAY',
    chainId: 8217,
  },
  celo: {
    key: 'celo',
    id: 14,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.celo,
    icon: CeloIcon,
    displayName: 'Celo',
    explorerUrl: 'https://explorer.celo.org/mainnet/',
    explorerName: 'Celo Explorer',
    gasToken: 'CELO',
    chainId: 42220,
  },
  near: {
    key: 'near',
    id: 15,
    context: Context.NEAR,
    contracts: CONTRACTS.MAINNET.near,
    icon: NearIcon,
    displayName: 'Near',
    explorerUrl: 'https://explorer.near.org/',
    explorerName: 'Near Explorer',
    gasToken: 'NEAR',
    chainId: 0,
  },
  injective: {
    key: 'injective',
    id: 19,
    context: Context.INJECTIVE,
    contracts: CONTRACTS.MAINNET.injective,
    icon: InjectiveIcon,
    displayName: 'Injective',
    explorerUrl: 'https://explorer.injective.network/',
    explorerName: 'Injective Explorer',
    gasToken: 'INJ',
    chainId: 0,
  },
  osmosis: {
    key: 'osmosis',
    id: 20,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.osmosis,
    icon: OsmosisIcon,
    displayName: 'Osmosis',
    explorerUrl: 'https://www.mintscan.io/osmosis',
    explorerName: 'MintScan',
    gasToken: 'OSMO',
    chainId: 0,
  },
  aptos: {
    key: 'aptos',
    id: 22,
    context: Context.APTOS,
    contracts: CONTRACTS.MAINNET.aptos,
    icon: AptosIcon,
    displayName: 'Aptos',
    explorerUrl: 'https://explorer.aptoslabs.com/',
    explorerName: 'Aptos Explorer',
    gasToken: 'APT',
    chainId: 0,
  },
  sui: {
    key: 'sui',
    id: 21,
    context: Context.OTHER,
    contracts: CONTRACTS.MAINNET.sui,
    icon: SuiIcon,
    displayName: 'SUI',
    explorerUrl: 'https://explorer.sui.io/',
    explorerName: 'SUI Explorer',
    gasToken: 'SUI',
    chainId: 0,
  },
  moonbeam: {
    key: 'moonbeam',
    id: 16,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.moonbeam,
    icon: MoonbeamIcon,
    displayName: 'Moonbeam',
    explorerUrl: 'https://moonscan.io/',
    explorerName: 'Moonscan',
    gasToken: 'GLMR',
    chainId: 1284,
  },
  neon: {
    key: 'neon',
    id: 17,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.neon,
    icon: NeonIcon,
    displayName: 'Neon',
    explorerUrl: 'https://neonscan.org/',
    explorerName: 'NeonScan',
    gasToken: 'NEON',
    chainId: 245022934,
  },
  terra2: {
    key: 'terra2',
    id: 18,
    context: Context.TERRA,
    contracts: CONTRACTS.MAINNET.terra2,
    icon: Terra2Icon,
    displayName: 'Terra 2',
    explorerUrl: 'https://atomscan.com/terra2',
    explorerName: 'ATOMScan',
    gasToken: 'ATOM',
    chainId: 0,
  },
  arbitrum: {
    key: 'arbitrum',
    id: 23,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.arbitrum,
    icon: ArbitrumIcon,
    displayName: 'Arbitrum',
    explorerUrl: 'https://arbiscan.io/',
    explorerName: 'ArbiScan',
    gasToken: 'ETH',
    chainId: 42161,
  },
  optimism: {
    key: 'optimism',
    id: 24,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.optimism,
    icon: '',
    displayName: 'Optimism',
    explorerUrl: 'https://optimistic.etherscan.io/',
    explorerName: 'Optimism Eplorer',
    gasToken: 'ETH',
    chainId: 10,
  },
  gnosis: {
    key: 'gnosis',
    id: 25,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.gnosis,
    icon: '',
    displayName: 'Gnosis',
    explorerUrl: 'https://gnosisscan.io/',
    explorerName: 'GnosisScan',
    gasToken: 'xDAI',
    chainId: 100,
  },
  pythnet: {
    key: 'pythnet',
    id: 26,
    context: Context.SOLANA,
    contracts: CONTRACTS.MAINNET.pythnet,
    icon: '',
    displayName: 'Pythnet',
    explorerUrl: '',
    explorerName: '',
    gasToken: '',
    chainId: 0,
  },
  xpla: {
    key: 'xpla',
    id: 28,
    context: Context.XPLA,
    contracts: CONTRACTS.MAINNET.xpla,
    icon: XplaIcon,
    displayName: 'XPLA',
    explorerUrl: 'https://explorer.xpla.io/',
    explorerName: 'XPLA Explorer',
    gasToken: 'XPLA',
    chainId: 0,
  },
  btc: {
    key: 'btc',
    id: 29,
    context: Context.OTHER,
    contracts: CONTRACTS.MAINNET.btc,
    icon: '',
    displayName: 'Bitcoin',
    explorerUrl: 'https://blockchair.com/bitcoin',
    explorerName: 'Blockchair',
    gasToken: 'BTC',
    chainId: 0,
  },
  wormchain: {
    key: 'wormchain',
    id: 3104,
    context: Context.OTHER,
    contracts: CONTRACTS.MAINNET.wormchain,
    icon: '',
    displayName: 'Wormchain',
    explorerUrl: '',
    explorerName: '',
    gasToken: '',
    chainId: 0,
  },
};

export const MAINNET_TOKENS: { [key: string]: TokenConfig } = {
  MATIC: {
    symbol: 'MATIC',
    icon: PolygonIcon,
    address: undefined,
    coinGeckoId: 'polygon',
    color: '#8247E5',
    decimals: 18,
  },
  WMATIC: {
    symbol: 'WMATIC',
    icon: PolygonIcon,
    address: '0x1234...5678',
    coinGeckoId: 'polygon',
    color: '#8247E5',
    decimals: 18,
  },
  SOL: {
    symbol: 'SOL',
    icon: SolanaIcon,
    address: '0x1234...5678',
    coinGeckoId: 'solana',
    color: '#28D4B5',
    decimals: 18,
  },
  WAVAX: {
    symbol: 'WAVAX',
    icon: AvaxIcon,
    address: '0x1234...5678',
    coinGeckoId: 'wrapped-avax',
    color: '#E84142',
    decimals: 18,
  },
  CELO: {
    symbol: 'CELO',
    icon: CeloIcon,
    address: '0x1234...5678',
    coinGeckoId: 'celo',
    color: '#35D07E',
    decimals: 18,
  },
  BNB: {
    symbol: 'BNB',
    icon: BnbIcon,
    address: '0x1234...5678',
    coinGeckoId: 'bnb',
    color: '#F3BA30',
    decimals: 18,
  },
};

const env: Environment = 'MAINNET';
const MAINNET_CONFIG: WormholeConfig = {
  env,
  rpcs: {
    solana: 'https://api.devnet.solana.com',
    ethereum: 'https://main-light.eth.linkpool.io',
  },
  chains: MAINNET,
};

export default MAINNET_CONFIG;
