import {
  Network as Environment,
  Contracts,
  CONTRACTS,
} from '@certusone/wormhole-sdk';
import { WormholeConfig, Context, ChainConfig } from '../types';

// https://book.wormhole.com/reference/contracts.html
export const MAINNET_CHAINS = {
  solana: 1,
  ethereum: 2,
  terra: 3,
  bsc: 4,
  polygon: 5,
  avalanche: 6,
  oasis: 7,
  algorand: 8,
  aurora: 9,
  fantom: 10,
  karura: 11,
  acala: 12,
  klaytn: 13,
  celo: 14,
  near: 15,
  moonbeam: 16,
  neon: 17,
  terra2: 18,
  injective: 19,
  osmosis: 20,
  sui: 21,
  aptos: 22,
  arbitrum: 23,
  optimism: 24,
  gnosis: 25,
  pythnet: 26,
  xpla: 28,
  btc: 29,
  wormchain: 3104,
} as const;

export type MainnetChainName = keyof typeof MAINNET_CHAINS;
export type MainnetChainId = (typeof MAINNET_CHAINS)[MainnetChainName];

export type ChainContracts = {
  [chain in MainnetChainName]: Contracts;
};

const MAINNET: { [chain in MainnetChainName]: ChainConfig } = {
  solana: {
    key: 'solana',
    id: 1,
    context: Context.SOLANA,
    contracts: CONTRACTS.MAINNET.solana,
    displayName: 'Solana',
    explorerUrl: 'https://explorer.solana.com/',
    explorerName: 'Solana Explorer',
    gasToken: 'SOL', // TODO:
    chainId: 0,
  },
  ethereum: {
    key: 'ethereum',
    id: 2,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.ethereum,
    displayName: 'Ethereum',
    explorerUrl: 'https://etherscan.io/',
    explorerName: 'Etherscan',
    gasToken: 'ETH',
    chainId: 1,
  },
  terra: {
    key: 'terra',
    id: 3,
    context: Context.TERRA,
    contracts: CONTRACTS.MAINNET.terra,
    displayName: 'Terra',
    explorerUrl: 'https://atomscan.com/terra',
    explorerName: 'ATOMScan',
    gasToken: 'ATOM',
    chainId: 0,
  },
  bsc: {
    key: 'bsc',
    id: 4,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.bsc,
    displayName: 'BSC',
    explorerUrl: 'https://bscscan.com/',
    explorerName: 'BscScan',
    gasToken: 'BNB',
    chainId: 56,
  },
  polygon: {
    key: 'polygon',
    id: 5,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.polygon,
    displayName: 'Polygon',
    explorerUrl: 'https://polygonscan.com/',
    explorerName: 'PolygonScan',
    gasToken: 'MATIC',
    chainId: 137,
  },
  avalanche: {
    key: 'avalanche',
    id: 6,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.avalanche,
    displayName: 'Avalanche',
    explorerUrl: 'https://snowtrace.io/',
    explorerName: 'Snowtrace',
    gasToken: 'WAVAX',
    chainId: 43114,
  },
  oasis: {
    key: 'oasis',
    id: 7,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.oasis,
    displayName: 'Oasis',
    explorerUrl: 'https://www.oasisscan.com/',
    explorerName: 'Oasis Scan',
    gasToken: 'ROSE',
    chainId: 26863,
  },
  algorand: {
    key: 'algorand',
    id: 8,
    context: Context.ALGORAND,
    contracts: CONTRACTS.MAINNET.algorand,
    displayName: 'Algorand',
    explorerUrl: 'https://algoexplorer.io/',
    explorerName: 'AlgoExplorer',
    gasToken: 'ALGO',
    chainId: 0,
  },
  aurora: {
    key: 'aurora',
    id: 9,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.aurora,
    displayName: 'Aurora',
    explorerUrl: 'https://explorer.mainnet.aurora.dev/',
    explorerName: 'Aurora Explorer',
    gasToken: 'NEAR',
    chainId: 1313161554,
  },
  fantom: {
    key: 'fantom',
    id: 10,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.fantom,
    displayName: 'Fantom',
    explorerUrl: 'https://ftmscan.com/',
    explorerName: 'FTMscan',
    gasToken: 'FTM',
    chainId: 250,
  },
  karura: {
    key: 'karura',
    id: 11,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.karura,
    displayName: 'Karura',
    explorerUrl: 'https://karura.subscan.io/',
    explorerName: 'Karura Explorer',
    gasToken: 'KAR',
    chainId: 686,
  },
  acala: {
    key: 'acala',
    id: 12,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.acala,
    displayName: 'Acala',
    explorerUrl: 'https://acala.subscan.io/',
    explorerName: 'Acala Explorer',
    gasToken: 'ACA',
    chainId: 787,
  },
  klaytn: {
    key: 'klaytn',
    id: 13,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.klaytn,
    displayName: 'Klaytn',
    explorerUrl: 'https://scope.klaytn.com/',
    explorerName: 'KlaytnScope',
    gasToken: 'KLAY',
    chainId: 8217,
  },
  celo: {
    key: 'celo',
    id: 14,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.celo,
    displayName: 'Celo',
    explorerUrl: 'https://explorer.celo.org/mainnet/',
    explorerName: 'Celo Explorer',
    gasToken: 'CELO',
    chainId: 42220,
  },
  near: {
    key: 'near',
    id: 15,
    context: Context.NEAR,
    contracts: CONTRACTS.MAINNET.near,
    displayName: 'Near',
    explorerUrl: 'https://explorer.near.org/',
    explorerName: 'Near Explorer',
    gasToken: 'NEAR',
    chainId: 0,
  },
  injective: {
    key: 'injective',
    id: 19,
    context: Context.INJECTIVE,
    contracts: CONTRACTS.MAINNET.injective,
    displayName: 'Injective',
    explorerUrl: 'https://explorer.injective.network/',
    explorerName: 'Injective Explorer',
    gasToken: 'INJ',
    chainId: 0,
  },
  osmosis: {
    key: 'osmosis',
    id: 20,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.osmosis,
    displayName: 'Osmosis',
    explorerUrl: 'https://www.mintscan.io/osmosis',
    explorerName: 'MintScan',
    gasToken: 'OSMO',
    chainId: 0,
  },
  aptos: {
    key: 'aptos',
    id: 22,
    context: Context.APTOS,
    contracts: CONTRACTS.MAINNET.aptos,
    displayName: 'Aptos',
    explorerUrl: 'https://explorer.aptoslabs.com/',
    explorerName: 'Aptos Explorer',
    gasToken: 'APT',
    chainId: 0,
  },
  sui: {
    key: 'sui',
    id: 21,
    context: Context.OTHER,
    contracts: CONTRACTS.MAINNET.sui,
    displayName: 'SUI',
    explorerUrl: 'https://explorer.sui.io/',
    explorerName: 'SUI Explorer',
    gasToken: 'SUI',
    chainId: 0,
  },
  moonbeam: {
    key: 'moonbeam',
    id: 16,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.moonbeam,
    displayName: 'Moonbeam',
    explorerUrl: 'https://moonscan.io/',
    explorerName: 'Moonscan',
    gasToken: 'GLMR',
    chainId: 1284,
  },
  neon: {
    key: 'neon',
    id: 17,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.neon,
    displayName: 'Neon',
    explorerUrl: 'https://neonscan.org/',
    explorerName: 'NeonScan',
    gasToken: 'NEON',
    chainId: 245022934,
  },
  terra2: {
    key: 'terra2',
    id: 18,
    context: Context.TERRA,
    contracts: CONTRACTS.MAINNET.terra2,
    displayName: 'Terra 2',
    explorerUrl: 'https://atomscan.com/terra2',
    explorerName: 'ATOMScan',
    gasToken: 'ATOM',
    chainId: 0,
  },
  arbitrum: {
    key: 'arbitrum',
    id: 23,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.arbitrum,
    displayName: 'Arbitrum',
    explorerUrl: 'https://arbiscan.io/',
    explorerName: 'ArbiScan',
    gasToken: 'ETH',
    chainId: 42161,
  },
  optimism: {
    key: 'optimism',
    id: 24,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.optimism,
    displayName: 'Optimism',
    explorerUrl: 'https://optimistic.etherscan.io/',
    explorerName: 'Optimism Eplorer',
    gasToken: 'ETH',
    chainId: 10,
  },
  gnosis: {
    key: 'gnosis',
    id: 25,
    context: Context.ETH,
    contracts: CONTRACTS.MAINNET.gnosis,
    displayName: 'Gnosis',
    explorerUrl: 'https://gnosisscan.io/',
    explorerName: 'GnosisScan',
    gasToken: 'xDAI',
    chainId: 100,
  },
  pythnet: {
    key: 'pythnet',
    id: 26,
    context: Context.SOLANA,
    contracts: CONTRACTS.MAINNET.pythnet,
    displayName: 'Pythnet',
    explorerUrl: '',
    explorerName: '',
    gasToken: '',
    chainId: 0,
  },
  xpla: {
    key: 'xpla',
    id: 28,
    context: Context.XPLA,
    contracts: CONTRACTS.MAINNET.xpla,
    displayName: 'XPLA',
    explorerUrl: 'https://explorer.xpla.io/',
    explorerName: 'XPLA Explorer',
    gasToken: 'XPLA',
    chainId: 0,
  },
  btc: {
    key: 'btc',
    id: 29,
    context: Context.OTHER,
    contracts: CONTRACTS.MAINNET.btc,
    displayName: 'Bitcoin',
    explorerUrl: 'https://blockchair.com/bitcoin',
    explorerName: 'Blockchair',
    gasToken: 'BTC',
    chainId: 0,
  },
  wormchain: {
    key: 'wormchain',
    id: 3104,
    context: Context.OTHER,
    contracts: CONTRACTS.MAINNET.wormchain,
    displayName: 'Wormchain',
    explorerUrl: '',
    explorerName: '',
    gasToken: '',
    chainId: 0,
  },
};

const env: Environment = 'MAINNET';
const MAINNET_CONFIG: WormholeConfig = {
  env,
  rpcs: {
    solana: 'https://api.devnet.solana.com',
    ethereum: 'https://main-light.eth.linkpool.io',
  },
  chains: MAINNET,
};

export default MAINNET_CONFIG;
