import { CONFIG } from '@wormhole-foundation/wormhole-connect-sdk';
import { NetworksConfig, TokenConfig, Icon } from './types';

const { chains } = CONFIG.MAINNET;

export const MAINNET_NETWORKS: NetworksConfig = {
  ethereum: {
    ...chains.ethereum!,
    icon: Icon.ETH,
    nativeToken: 'ETH',
    automaticRelayer: true,
  },
  bsc: {
    ...chains.bsc!,
    icon: Icon.BSC,
    nativeToken: 'BNB',
    automaticRelayer: true,
  },
  polygon: {
    ...chains.polygon!,
    icon: Icon.POLYGON,
    nativeToken: 'MATIC',
    automaticRelayer: true,
  },
  avalanche: {
    ...chains.avalanche!,
    icon: Icon.AVAX,
    nativeToken: 'AVAX',
    automaticRelayer: true,
  },
  fantom: {
    ...chains.fantom!,
    icon: Icon.FANTOM,
    nativeToken: 'FTM',
    automaticRelayer: true,
  },
  celo: {
    ...chains.celo!,
    icon: Icon.CELO,
    nativeToken: 'CELO',
    automaticRelayer: true,
  },
  solana: {
    ...chains.solana!,
    icon: Icon.SOLANA,
    nativeToken: 'SOL',
    automaticRelayer: false,
  },
};

export const MAINNET_TOKENS: { [key: string]: TokenConfig } = {
  ETH: {
    symbol: 'ETH',
    nativeNetwork: 'ethereum',
    icon: Icon.ETH,
    coinGeckoId: 'ethereum',
    color: '#62688F',
    decimals: 9,
    solDecimals: 8,
    wrappedAsset: 'WETH',
  },
  WETH: {
    symbol: 'WETH',
    nativeNetwork: 'ethereum',
    icon: Icon.ETH,
    tokenId: {
      chain: 'ethereum',
      address: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
    },
    coinGeckoId: 'ethereum',
    color: '#62688F',
    decimals: 18,
    solDecimals: 8,
  },
  MATIC: {
    symbol: 'MATIC',
    nativeNetwork: 'polygon',
    icon: Icon.POLYGON,
    coinGeckoId: 'matic-network',
    color: '#8247E5',
    decimals: 18,
    solDecimals: 8,
    wrappedAsset: 'WMATIC',
  },
  WMATIC: {
    symbol: 'WMATIC',
    nativeNetwork: 'polygon',
    icon: Icon.POLYGON,
    tokenId: {
      chain: 'polygon',
      address: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
    },
    coinGeckoId: 'matic-network',
    color: '#8247E5',
    decimals: 18,
    solDecimals: 8,
  },
  BNB: {
    symbol: 'BNB',
    nativeNetwork: 'bsc',
    icon: Icon.BNB,
    coinGeckoId: 'binancecoin',
    color: '#F3BA30',
    decimals: 18,
    solDecimals: 8,
    wrappedAsset: 'WBNB',
  },
  WBNB: {
    symbol: 'WBNB',
    nativeNetwork: 'bsc',
    icon: Icon.BNB,
    tokenId: {
      chain: 'bsc',
      address: '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
    },
    coinGeckoId: 'binancecoin',
    color: '#F3BA30',
    decimals: 18,
    solDecimals: 8,
  },
  AVAX: {
    symbol: 'AVAX',
    nativeNetwork: 'avalanche',
    icon: Icon.AVAX,
    coinGeckoId: 'avalanche-2',
    color: '#E84141',
    decimals: 18,
    solDecimals: 8,
  },
  WAVAX: {
    symbol: 'WAVAX',
    nativeNetwork: 'avalanche',
    icon: Icon.AVAX,
    tokenId: {
      chain: 'avalanche',
      address: '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7',
    },
    coinGeckoId: 'avalanche-2',
    color: '#E84141',
    decimals: 18,
    solDecimals: 8,
  },
  FTM: {
    symbol: 'FTM',
    nativeNetwork: 'fantom',
    icon: Icon.FANTOM,
    coinGeckoId: 'fantom',
    color: '#12B4EC',
    decimals: 18,
    solDecimals: 8,
    wrappedAsset: 'WFTM',
  },
  WFTM: {
    symbol: 'WFTM',
    nativeNetwork: 'fantom',
    icon: Icon.FANTOM,
    tokenId: {
      chain: 'fantom',
      address: '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83',
    },
    coinGeckoId: 'fantom',
    color: '#12B4EC',
    decimals: 18,
    solDecimals: 8,
  },
  CELO: {
    symbol: 'CELO',
    nativeNetwork: 'celo',
    icon: Icon.CELO,
    tokenId: {
      chain: 'celo',
      address: '0x471ece3750da237f93b8e339c536989b8978a438',
    },
    coinGeckoId: 'celo',
    color: '#35D07E',
    decimals: 18,
    solDecimals: 8,
  },
  SOL: {
    symbol: 'SOL',
    nativeNetwork: 'solana',
    icon: Icon.SOLANA,
    coinGeckoId: 'solana',
    color: '#8457EF',
    decimals: 9,
    solDecimals: 9,
    wrappedAsset: 'WSOL',
  },
  WSOL: {
    symbol: 'WSOL',
    nativeNetwork: 'solana',
    tokenId: {
      chain: 'solana',
      address: 'So11111111111111111111111111111111111111112',
    },
    icon: Icon.SOLANA,
    coinGeckoId: 'solana',
    color: '#8457EF',
    decimals: 9,
    solDecimals: 9,
  },
};
