/// <reference types="vite/client" />

interface ImportMetaEnv {
  // env
  REACT_APP_CONNECT_ENV: string;

  // wallet connect
  REACT_APP_WALLET_CONNECT_PROJECT_ID: string;

  // mainnet
  REACT_APP_ETHEREUM_RPC: string;
  REACT_APP_SOLANA_RPC: string;
  REACT_APP_POLYGON_RPC: string;
  REACT_APP_BSC_RPC: string;
  REACT_APP_AVALANCHE_RPC: string;
  REACT_APP_FANTOM_RPC: string;
  REACT_APP_CELO_RPC: string;
  REACT_APP_MOONBEAM_RPC: string;
  REACT_APP_SUI_RPC: string;
  REACT_APP_APTOS_RPC: string;
  REACT_APP_BASE_RPC: string;
  REACT_APP_KLAYTN_RPC: string;
  REACT_APP_ARBITRUM_RPC: string;
  REACT_APP_OPTIMISM_RPC: string;
  REACT_APP_SCROLL_RPC: string;
  REACT_APP_BLAST_RPC: string;
  REACT_APP_XLAYER_RPC: string;
  REACT_APP_MANTLE_RPC: string;
  REACT_APP_WORLDCHAIN_RPC: string;
  REACT_APP_UNICHAIN_RPC: string;

  // testnet
  REACT_APP_SEPOLIA_RPC: string;
  REACT_APP_BSC_TESTNET_RPC: string;
  REACT_APP_FUJI_RPC: string;
  REACT_APP_FANTOM_TESTNET_RPC: string;
  REACT_APP_ALFAJORES_RPC: string;
  REACT_APP_SOLANA_DEVNET_RPC: string;
  REACT_APP_MOONBASE_RPC: string;
  REACT_APP_SUI_TESTNET_RPC: string;
  REACT_APP_APTOS_TESTNET_RPC: string;
  REACT_APP_BASE_SEPOLIA_RPC: string;
  REACT_APP_KLAYTN_TESTNET_RPC: string;
  REACT_APP_ARBITRUM_SEPOLIA_RPC: string;
  REACT_APP_OPTIMISM_SEPOLIA_RPC: string;
  REACT_APP_SCROLL_TESTNET_RPC: string;
  REACT_APP_BLAST_TESTNET_RPC: string;
  REACT_APP_XLAYER_TESTNET_RPC: string;
  REACT_APP_MANTLE_TESTNET_RPC: string;
  REACT_APP_WORLDCHAIN_TESTNET_RPC: string;
  REACT_APP_UNICHAIN_TESTNET_RPC: string;

  // devnet
  REACT_APP_ETHEREUM_DEVNET_RPC: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
