import { ChainsConfig } from '../types';

export const MAINNET_CHAINS: ChainsConfig = {
  Ethereum: {
    displayName: 'Ethereum',
    sdkName: 'Ethereum',
    explorerUrl: 'https://etherscan.io/',
    explorerName: 'Etherscan',
    icon: 'Ethereum',
    symbol: 'ETH',
  },
  Bsc: {
    displayName: 'BSC',
    sdkName: 'Bsc',
    explorerUrl: 'https://bscscan.com/',
    explorerName: 'BscScan',
    icon: 'Bsc',
    symbol: 'BSC',
  },
  Polygon: {
    displayName: 'Polygon',
    sdkName: 'Polygon',
    explorerUrl: 'https://polygonscan.com/',
    explorerName: 'PolygonScan',
    icon: 'Polygon',
    symbol: 'POL',
  },
  Avalanche: {
    displayName: 'Avalanche',
    sdkName: 'Avalanche',
    explorerUrl: 'https://avascan.info/blockchain/c/',
    explorerName: 'Avascan',
    icon: 'Avalanche',
    symbol: 'AVAX',
  },
  Fantom: {
    displayName: 'Fantom',
    sdkName: 'Fantom',
    explorerUrl: 'https://explorer.fantom.network/',
    explorerName: 'Fantom Explorer',
    icon: 'Fantom',
    symbol: 'FTM',
  },
  Celo: {
    displayName: 'Celo',
    sdkName: 'Celo',
    explorerUrl: 'https://explorer.celo.org/mainnet/',
    explorerName: 'Celo Explorer',
    icon: 'Celo',
    symbol: 'CELO',
  },
  Moonbeam: {
    displayName: 'Moonbeam',
    sdkName: 'Moonbeam',
    explorerUrl: 'https://moonscan.io/',
    explorerName: 'Moonscan',
    icon: 'Moonbeam',
    symbol: 'GLMR',
  },
  Solana: {
    displayName: 'Solana',
    sdkName: 'Solana',
    explorerUrl: 'https://explorer.solana.com/',
    explorerName: 'Solana Explorer',
    icon: 'Solana',
    symbol: 'SOL',
  },
  Sui: {
    displayName: 'Sui',
    sdkName: 'Sui',
    explorerUrl: 'https://suiscan.xyz/',
    explorerName: 'Suiscan',
    icon: 'Sui',
    symbol: 'SUI',
  },
  Aptos: {
    displayName: 'Aptos',
    sdkName: 'Aptos',
    explorerUrl: 'https://explorer.aptoslabs.com/',
    explorerName: 'Aptos Explorer',
    icon: 'Aptos',
    symbol: 'APT',
  },
  Base: {
    displayName: 'Base',
    sdkName: 'Base',
    explorerUrl: 'https://basescan.org/',
    explorerName: 'BaseScan',
    icon: 'Base',
    symbol: 'BASE',
  },
  Arbitrum: {
    displayName: 'Arbitrum',
    sdkName: 'Arbitrum',
    explorerUrl: 'https://arbiscan.io/',
    explorerName: 'Arbitrum Explorer',
    icon: 'Arbitrum',
    symbol: 'ARB',
  },
  Optimism: {
    displayName: 'Optimism',
    sdkName: 'Optimism',
    explorerUrl: 'https://optimistic.etherscan.io/',
    explorerName: 'Optimistic Etherscan',
    icon: 'Optimism',
    symbol: 'OP',
  },
  Klaytn: {
    displayName: 'Kaia',
    sdkName: 'Klaytn',
    explorerUrl: 'https://kaiascope.com/',
    explorerName: 'Kaia Scope',
    icon: 'Klaytn',
    symbol: 'KLAY',
  },
  Scroll: {
    displayName: 'Scroll',
    sdkName: 'Scroll',
    explorerUrl: 'https://scrollscan.com/',
    explorerName: 'Scrollscan',
    icon: 'Scroll',
    symbol: 'SCR',
  },
  Blast: {
    displayName: 'Blast',
    sdkName: 'Blast',
    explorerUrl: 'https://blastscan.io/',
    explorerName: 'Blastscan',
    icon: 'Blast',
    symbol: 'BLAST',
  },
  Xlayer: {
    displayName: 'X Layer',
    sdkName: 'Xlayer',
    explorerUrl: 'https://www.okx.com/web3/explorer/xlayer/',
    explorerName: 'OKX Explorer',
    icon: 'Xlayer',
    symbol: 'OKX',
  },
  Mantle: {
    displayName: 'Mantle',
    sdkName: 'Mantle',
    explorerUrl: 'https://explorer.mantle.xyz/',
    explorerName: 'Mantle Explorer',
    icon: 'Mantle',
    symbol: 'MNT',
  },
  Worldchain: {
    displayName: 'World Chain',
    sdkName: 'Worldchain',
    explorerUrl: 'https://worldscan.org/',
    explorerName: 'World Scan',
    icon: 'Worldchain',
    symbol: 'WORLD',
  },
  Unichain: {
    displayName: 'Unichain',
    sdkName: 'Unichain',
    explorerUrl: 'https://uniscan.xyz/',
    explorerName: 'Uniscan',
    icon: 'Unichain',
    symbol: 'UNI',
  },
  Berachain: {
    displayName: 'Berachain',
    sdkName: 'Berachain',
    explorerUrl: 'https://berascan.com/',
    explorerName: 'Berascan',
    icon: 'Berachain',
    symbol: 'BERA',
  },
  Linea: {
    displayName: 'Linea',
    sdkName: 'Linea',
    explorerUrl: 'https://lineascan.build/',
    explorerName: 'Lineascan',
    icon: 'Linea',
    symbol: 'LINEA',
  },
  Sonic: {
    displayName: 'Sonic',
    sdkName: 'Sonic',
    explorerUrl: 'https://sonicscan.org/',
    explorerName: 'Sonicscan',
    icon: 'Sonic',
    symbol: 'S',
  },
};
