import type { ChainsConfig } from '../types';

export const MAINNET_CHAINS: ChainsConfig = {
  Ethereum: {
    displayName: 'Ethereum',
    sdkName: 'Ethereum',
    explorerUrl: 'https://etherscan.io/',
    explorerName: 'Etherscan',
    icon: 'Ethereum',
    symbol: 'ETH',
    gasReserve: '0.01',
    coingeckoPlatformId: 1,
    coingeckoNativeTokenId: 'ethereum',
  },
  Bsc: {
    displayName: 'BNB',
    sdkName: 'Bsc',
    explorerUrl: 'https://bscscan.com/',
    explorerName: 'BscScan',
    icon: 'Bsc',
    symbol: 'BSC',
    gasReserve: '0.01',
    coingeckoPlatformId: 56,
    coingeckoNativeTokenId: 'binancecoin',
  },
  Polygon: {
    displayName: 'Polygon',
    sdkName: 'Polygon',
    explorerUrl: 'https://polygonscan.com/',
    explorerName: 'PolygonScan',
    icon: 'Polygon',
    symbol: 'POL',
    gasReserve: '0.01',
    coingeckoPlatformId: 137,
    coingeckoNativeTokenId: 'polygon-ecosystem-token',
  },
  Avalanche: {
    displayName: 'Avalanche',
    sdkName: 'Avalanche',
    explorerUrl: 'https://snowtrace.io/',
    explorerName: 'Snowtrace',
    icon: 'Avalanche',
    symbol: 'AVAX',
    gasReserve: '0.01',
    coingeckoPlatformId: 43114,
    coingeckoNativeTokenId: 'avalanche-2',
  },
  Fantom: {
    displayName: 'Fantom',
    sdkName: 'Fantom',
    explorerUrl: 'https://explorer.fantom.network/',
    explorerName: 'Fantom Explorer',
    icon: 'Fantom',
    symbol: 'FTM',
    coingeckoPlatformId: 250,
    coingeckoNativeTokenId: 'fantom',
  },
  Celo: {
    displayName: 'Celo',
    sdkName: 'Celo',
    explorerUrl: 'https://explorer.celo.org/mainnet/',
    explorerName: 'Celo Explorer',
    icon: 'Celo',
    symbol: 'CELO',
    gasReserve: '0.01',
    coingeckoPlatformId: 42220,
    coingeckoNativeTokenId: 'celo',
  },
  Moonbeam: {
    displayName: 'Moonbeam',
    sdkName: 'Moonbeam',
    explorerUrl: 'https://moonscan.io/',
    explorerName: 'Moonscan',
    icon: 'Moonbeam',
    symbol: 'GLMR',
    gasReserve: '0.03',
    coingeckoPlatformId: 1284,
    coingeckoNativeTokenId: 'moonbeam',
  },
  Solana: {
    displayName: 'Solana',
    sdkName: 'Solana',
    explorerUrl: 'https://explorer.solana.com/',
    explorerName: 'Solana Explorer',
    icon: 'Solana',
    symbol: 'SOL',
    gasReserve: '0.01',
    coingeckoPlatformId: 'solana',
    coingeckoNativeTokenId: 'solana',
  },
  Sui: {
    displayName: 'Sui',
    sdkName: 'Sui',
    explorerUrl: 'https://suiscan.xyz/',
    explorerName: 'Suiscan',
    icon: 'Sui',
    symbol: 'SUI',
    gasReserve: '0.01',
    coingeckoPlatformId: 'sui',
    coingeckoNativeTokenId: 'sui',
  },
  Aptos: {
    displayName: 'Aptos',
    sdkName: 'Aptos',
    explorerUrl: 'https://explorer.aptoslabs.com/',
    explorerName: 'Aptos Explorer',
    icon: 'Aptos',
    symbol: 'APT',
    gasReserve: '0.01',
    coingeckoPlatformId: 'aptos',
    coingeckoNativeTokenId: 'aptos',
  },
  Base: {
    displayName: 'Base',
    sdkName: 'Base',
    explorerUrl: 'https://basescan.org/',
    explorerName: 'BaseScan',
    icon: 'Base',
    symbol: 'BASE',
    gasReserve: '0.001',
    coingeckoPlatformId: 8453,
    coingeckoNativeTokenId: 'ethereum',
  },
  Arbitrum: {
    displayName: 'Arbitrum',
    sdkName: 'Arbitrum',
    explorerUrl: 'https://arbiscan.io/',
    explorerName: 'Arbitrum Explorer',
    icon: 'Arbitrum',
    symbol: 'ARB',
    gasReserve: '0.001',
    coingeckoPlatformId: 42161,
    coingeckoNativeTokenId: 'ethereum',
  },
  Optimism: {
    displayName: 'Optimism',
    sdkName: 'Optimism',
    explorerUrl: 'https://optimistic.etherscan.io/',
    explorerName: 'Optimistic Etherscan',
    icon: 'Optimism',
    symbol: 'OP',
    gasReserve: '0.001',
    coingeckoPlatformId: 10,
    coingeckoNativeTokenId: 'ethereum',
  },
  Klaytn: {
    displayName: 'Kaia',
    sdkName: 'Klaytn',
    explorerUrl: 'https://kaiascan.io/',
    explorerName: 'KaiaScan',
    icon: 'Klaytn',
    symbol: 'KAIA',
    gasReserve: '0.01',
    coingeckoPlatformId: 8217,
    coingeckoNativeTokenId: 'kaia',
  },
  Scroll: {
    displayName: 'Scroll',
    sdkName: 'Scroll',
    explorerUrl: 'https://scrollscan.com/',
    explorerName: 'Scrollscan',
    icon: 'Scroll',
    symbol: 'SCR',
    gasReserve: '0.001',
    coingeckoPlatformId: 534352,
    coingeckoNativeTokenId: 'ethereum',
  },
  Xlayer: {
    displayName: 'X Layer',
    sdkName: 'Xlayer',
    explorerUrl: 'https://www.okx.com/web3/explorer/xlayer/',
    explorerName: 'OKX Explorer',
    icon: 'Xlayer',
    symbol: 'OKX',
    gasReserve: '0.001',
    coingeckoPlatformId: 196,
    coingeckoNativeTokenId: 'okb',
  },
  Mantle: {
    displayName: 'Mantle',
    sdkName: 'Mantle',
    explorerUrl: 'https://explorer.mantle.xyz/',
    explorerName: 'Mantle Explorer',
    icon: 'Mantle',
    symbol: 'MNT',
    gasReserve: '0.001',
    coingeckoPlatformId: 5000,
    coingeckoNativeTokenId: 'mantle',
  },
  Worldchain: {
    displayName: 'World Chain',
    sdkName: 'Worldchain',
    explorerUrl: 'https://worldscan.org/',
    explorerName: 'World Scan',
    icon: 'Worldchain',
    symbol: 'WORLD',
    coingeckoPlatformId: 480,
    coingeckoNativeTokenId: 'ethereum',
  },
  Unichain: {
    displayName: 'Unichain',
    sdkName: 'Unichain',
    explorerUrl: 'https://uniscan.xyz/',
    explorerName: 'Uniscan',
    icon: 'Unichain',
    symbol: 'UNI',
    coingeckoPlatformId: 1301,
    coingeckoNativeTokenId: 'ethereum',
  },
  Berachain: {
    displayName: 'Berachain',
    sdkName: 'Berachain',
    explorerUrl: 'https://berascan.com/',
    explorerName: 'Berascan',
    icon: 'Berachain',
    symbol: 'BERA',
    coingeckoPlatformId: 80084,
    coingeckoNativeTokenId: 'berachain-bera',
  },
  Ink: {
    displayName: 'Ink',
    sdkName: 'Ink',
    explorerUrl: 'https://explorer.inkonchain.com/',
    explorerName: 'Ink Explorer',
    icon: 'Ink',
    symbol: 'INK',
    coingeckoPlatformId: 'ink',
    coingeckoNativeTokenId: 'ethereum',
  },
  Linea: {
    displayName: 'Linea',
    sdkName: 'Linea',
    explorerUrl: 'https://lineascan.build/',
    explorerName: 'Lineascan',
    icon: 'Linea',
    symbol: 'LINEA',
    coingeckoPlatformId: 59144,
    coingeckoNativeTokenId: 'ethereum',
  },
  Sonic: {
    displayName: 'Sonic',
    sdkName: 'Sonic',
    explorerUrl: 'https://sonicscan.org/',
    explorerName: 'Sonicscan',
    icon: 'Sonic',
    symbol: 'S',
    coingeckoPlatformId: 146,
    coingeckoNativeTokenId: 'sonic',
  },
  Mezo: {
    displayName: 'Mezo',
    sdkName: 'Mezo',
    explorerUrl: 'https://explorer.mezo.org',
    explorerName: 'Mezo Explorer',
    icon: 'Mezo',
    symbol: 'BTC',
    coingeckoPlatformId: 'mezo',
    coingeckoNativeTokenId: 'tbtc',
  },
  Seievm: {
    displayName: 'SeiEVM',
    sdkName: 'Seievm',
    explorerUrl: 'https://seitrace.com/?chain=pacific-1',
    explorerName: 'Seitrace',
    icon: 'Seievm',
    symbol: 'SEI',
    coingeckoPlatformId: 1329,
    coingeckoNativeTokenId: 'sei',
  },
  Plume: {
    displayName: 'Plume',
    sdkName: 'Plume',
    explorerUrl: 'https://explorer.plume.org',
    explorerName: 'Plume Explorer',
    icon: 'Plume',
    symbol: 'PLUME',
    coingeckoPlatformId: 'plume-network',
    coingeckoNativeTokenId: 'plume',
  },
  HyperEVM: {
    displayName: 'HyperEVM',
    sdkName: 'HyperEVM',
    explorerUrl: 'https://hyperevmscan.io/',
    explorerName: 'HyperEVMScan',
    icon: 'HyperEVM',
    symbol: 'HYPE',
    coingeckoPlatformId: 'hyperevm',
    coingeckoNativeTokenId: 'hyperliquid',
  },
  HyperCore: {
    displayName: 'HyperCore',
    sdkName: 'HyperCore',
    explorerUrl: 'https://app.hyperliquid.xyz/explorer/',
    explorerName: 'Hyperliquid Explorer',
    icon: 'HyperCore',
    symbol: 'HyperCore',
    coingeckoPlatformId: 'hypercore',
    coingeckoNativeTokenId: 'usd-coin',
  },
  XRPLEVM: {
    displayName: 'XRPL EVM',
    sdkName: 'XRPLEVM',
    explorerUrl: 'https://explorer.xrplevm.org/',
    explorerName: 'XRPL EVM Explorer',
    icon: 'XRPLEVM',
    symbol: 'XRP',
    gasReserve: '0.01',
    coingeckoPlatformId: 'xrpl-evm-sidechain',
    coingeckoNativeTokenId: 'xrp',
  },
  CreditCoin: {
    displayName: 'Creditcoin',
    sdkName: 'CreditCoin',
    explorerUrl: 'https://creditcoin.blockscout.com',
    explorerName: 'Blockscout',
    icon: 'CreditCoin',
    symbol: 'CTC',
    coingeckoPlatformId: 'creditcoin',
    coingeckoNativeTokenId: 'creditcoin',
  },
  Fogo: {
    displayName: 'Fogo',
    sdkName: 'Fogo',
    explorerUrl: 'https://explorer.fogo.io/',
    explorerName: 'Fogo Explorer',
    icon: 'Fogo',
    symbol: 'FOGO',
    gasReserve: '0.01',
    coingeckoPlatformId: 'fogo',
    coingeckoNativeTokenId: 'fogo',
  },
  Monad: {
    displayName: 'Monad',
    sdkName: 'Monad',
    explorerUrl: 'https://monadvision.com/',
    explorerName: 'MonadVision',
    icon: 'Monad',
    symbol: 'MON',
    gasReserve: '0.01',
    coingeckoPlatformId: 'monad',
    coingeckoNativeTokenId: 'monad',
  },
  MegaETH: {
    displayName: 'MegaETH',
    sdkName: 'MegaETH',
    explorerUrl: 'https://megaeth-testnet-v3.blockscout.com/',
    explorerName: 'Blockscout',
    icon: 'MegaETH',
    symbol: 'MEGA',
    gasReserve: '0.001',
    coingeckoPlatformId: 'megaeth',
    coingeckoNativeTokenId: 'ethereum',
  },
};
