import {
  Commitment,
  Connection,
  Keypair,
  PublicKey,
  PublicKeyInitData,
  Transaction,
} from '@solana/web3.js';
import {
  SignTransaction,
  modifySignTransaction,
  TransactionSignatureAndResponse,
  PreparedTransactions,
  TransactionWithIndex,
  sendAndConfirmTransactions,
} from './utils';
import { addComputeBudget } from './computeBudget';
import {
  createPostVaaInstruction,
  createVerifySignaturesInstructions,
  derivePostedVaaKey,
  pendingSignatureVerificationTxs,
} from './wormhole';
import { isBytes, ParsedVaa, parseVaa, SignedVaa } from '../../../vaa/wormhole';

/**
 * @category Solana
 */
export async function postVaaWithRetry(
  connection: Connection,
  signTransaction: SignTransaction,
  wormholeProgramId: PublicKeyInitData,
  payer: PublicKeyInitData,
  vaa: Buffer,
  maxRetries?: number,
  commitment?: Commitment,
): Promise<TransactionSignatureAndResponse[]> {
  try {
    // Check if the VAA has already been posted
    const parsedVaa = parseVaa(vaa);
    const postedVaaAddress = derivePostedVaaKey(
      wormholeProgramId,
      parsedVaa.hash,
    );
    const postedVaa = await connection.getAccountInfo(postedVaaAddress);
    if (postedVaa !== null) {
      return [];
    }
  } catch (e) {
    console.error('Failed to check if VAA has already been posted:', e);
  }
  const { unsignedTransactions, signers } =
    await createPostSignedVaaTransactions(
      connection,
      wormholeProgramId,
      payer,
      vaa,
      commitment,
    );
  const postVaaTransaction = unsignedTransactions.pop();
  if (!postVaaTransaction) throw new Error('No postVaaTransaction');
  postVaaTransaction.feePayer = new PublicKey(payer);

  for (const unsignedTransaction of unsignedTransactions) {
    unsignedTransaction.feePayer = new PublicKey(payer);
    await addComputeBudget(connection, unsignedTransaction, [], 0.75, 1, true);
  }
  const responses = await sendAndConfirmTransactions(
    connection,
    modifySignTransaction(signTransaction, ...signers),
    payer.toString(),
    transactionsNotPresent.map((tx: TransactionWithIndex) => tx.transaction),
<<<<<<< HEAD
    maxRetries,
    commitment,
=======
    { maxRetries, commitment },
>>>>>>> 5ba3050 (Update sendAndConfirm function)
  );
  if (responses.errors && responses.errors?.length > 0)
    printError(responses.errors);

  //While the signature_set is used to create the final instruction, it doesn't need to sign it.
<<<<<<< HEAD
  await addComputeBudget(connection, postVaaTransaction, [], 0.75, 1, true);
  responses.push(
    ...(await sendAndConfirmTransactionsWithRetry(
      connection,
      signTransaction,
      payer.toString(),
      [postVaaTransaction.transaction],
      maxRetries,
      commitment,
    )),
=======
  await addComputeBudget(connection, postVaaTransaction.transaction);
  const postVaaResponse = await sendAndConfirmTransactions(
    connection,
    signTransaction,
    payer.toString(),
    [postVaaTransaction.transaction],
    { maxRetries, commitment },
>>>>>>> 5ba3050 (Update sendAndConfirm function)
  );
  responses.result.push(postVaaResponse.result[0]);
  if (postVaaResponse.errors && postVaaResponse.errors?.length > 0)
    printError(postVaaResponse.errors);

  return responses.result;
}

/**
 * @category Solana
 *
 * Send transactions for `verify_signatures` and `post_vaa` instructions.
 *
 * Using a signed VAA, execute transactions generated by {@link verifySignatures} and
 * {@link postVaa}. At most 4 transactions are sent (up to 3 from signature verification
 * and 1 to post VAA data to an account).
 *
 * @param {Connection} connection - Solana web3 connection
 * @param {PublicKeyInitData} wormholeProgramId - wormhole program address
 * @param {web3.Keypair} payer - transaction signer address
 * @param {Buffer} signedVaa - bytes of signed VAA
 * @param {Commitment} [options] - Solana commitment
 *
 */
export async function createPostSignedVaaTransactions(
  connection: Connection,
  wormholeProgramId: PublicKeyInitData,
  payer: PublicKeyInitData,
  vaa: SignedVaa | ParsedVaa,
  commitment?: Commitment,
): Promise<PreparedTransactions> {
  const parsed = isBytes(vaa) ? parseVaa(vaa) : vaa;
  const signatureSet = Keypair.generate();

  const verifySignaturesInstructions = await createVerifySignaturesInstructions(
    connection,
    wormholeProgramId,
    payer,
    parsed,
    signatureSet.publicKey,
    commitment,
  );

  const unsignedTransactions: TransactionWithIndex[] = [];
  for (let i = 0; i < verifySignaturesInstructions.length; i++) {
    const tx = new Transaction();
    tx.add(...verifySignaturesInstructions[i].instructions);

    unsignedTransactions.push({
      transaction: tx,
      index: i,
      signatureIndexes: verifySignaturesInstructions[i].signatureIndexes,
    });
  }

  const postVaaTx = new Transaction();
  postVaaTx.add(
    createPostVaaInstruction(
      connection,
      wormholeProgramId,
      payer,
      parsed,
      signatureSet.publicKey,
    ),
  );

  unsignedTransactions.push({
    transaction: postVaaTx,
    index: verifySignaturesInstructions.length,
    signatureIndexes: [],
  });
  return {
    unsignedTransactions,
    signers: [signatureSet],
  };
}

function printError(errors: Error[]) {
  throw new Error(
    'Error posting VAA to Solana \n' +
      errors.map((error) => error.toString()).join('\n'),
  );
}
