name: Build

on:
  pull_request:
  push:
    branches:
      - development
      - staging
      - production
      - mainnet

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: npm ci
        working-directory: wormhole-connect
      - run: npm run lint:ci
        working-directory: wormhole-connect
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: npm ci
        working-directory: wormhole-connect
      - run: npm test
        working-directory: wormhole-connect
        env:
          REACT_APP_SOLANA_RPC: ${{ vars.REACT_APP_SOLANA_RPC }}

  check-sdn-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: echo hi #npm i prettier && npm run checksdn
        working-directory: wormhole-connect

  check-token-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: npm ci
        working-directory: wormhole-connect
      - run: npx tsx scripts/checkForeignAssetsConfig.ts
        working-directory: wormhole-connect
  build-hosted:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: npm ci
        working-directory: wormhole-connect
      - run: npm run build:hosted
        working-directory: wormhole-connect
  build-library:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: npm ci
        working-directory: wormhole-connect
      - run: npm run build:lib
        working-directory: wormhole-connect
