name: Build

on:
  pull_request:
  push:
    branches:
      - development
      - staging
      - production
      - mainnet

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: cd wormhole-connect
      - run: pwd; ls;
      - run: npm ci
      - run: npm run lint:ci
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: cd wormhole-connect
      - run: npm ci
      - run: npm test
        env:
          REACT_APP_SOLANA_RPC: ${{ vars.REACT_APP_SOLANA_RPC }}

  check-sdn-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: cd wormhole-connect #&& npm i prettier && npm run checksdn

  check-token-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: cd wormhole-connect
      - run: npx tsx scripts/checkForeignAssetsConfig.ts
  build-hosted:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: cd wormhole-connect
      - run: npm ci
      - run: npm run build:hosted
  build-library:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "wormhole-connect/package-lock.json"
      - run: cd wormhole-connect
      - run: npm ci
      - run: npm run build:lib
