name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tagged version to release.'
        required: true
        type: 'string'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication with npm
      contents: read

    defaults:
      run:
        working-directory: './'

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run lint:ci
      - run: |
          IFS='@' read -a strarr <<< $(git describe --tags)
          sed  -i "s/\"version\": .*/\"version\": \"${strarr[1]}$(echo $([ ${strarr[0]} == "production" ] && echo "" || echo "-${strarr[0]}"))\",/" package.json
          npm run build:lib
          npm run build:hosted
          npm publish --tag $(echo $([ ${strarr[0]} == "production" ] && echo "latest" || echo ${strarr[0]})) --access public
