name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tagged version to release.'
        required: true
        type: 'string'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.4'
      - run: bun ci
      - run: bun run lint:ci
      - run: |
          IFS='@' read -a strarr <<< $(git describe --tags)
          sed  -i "s/\"version\": .*/\"version\": \"${strarr[1]}$(echo $([ ${strarr[0]} == "production" ] && echo "" || echo "-${strarr[0]}"))\",/" package.json
          bun run build:lib
          bun run build:hosted
          npm publish --tag $(echo $([ ${strarr[0]} == "production" ] && echo "latest" || echo ${strarr[0]})) --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
