name: Run tests

on: [push, pull_request]

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        working-directory: ./wormhole-connect
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        working-directory: ./wormhole-connect
        run: npm run test
